
POST http://localhost:3001/api/v1/user/create
Content-Type: application/json

{
    "email":"dfsdfs@dfs.com",
    "username":"dfsfsf",
    "password":"sdfgvsd",
    "conformPassword":"svsddcvv"
}
###
POST http://localhost:3001/user/create
Content-Type: application/json

{
    "email":"dfsdfs@dfs.com",
    "username":"dfsfsf",
    "password":"sdfgvsd",
    "conformPassword":"svsddcvv"
}